### ISSUE TITLE
Make notifications messages support clickable urls

### ISSUE THREAD

**Issue by smeddinck** [MORE-Platform/more-app-multiplatform#208]
e.g. with media or app links both in the notification area of the phone os (if possibly) and in the MORE app (certainly)

**Comment by andresgruber** [comment]
@smeddinck, @alireza-dhp : the proposed feature is not yet specified in a way that one can start implementing it. The following questions may help you to refine the feature:

- Will such a message contain title, body and (new) a link as a separate field in the API and in the study manager or would it be sufficient to use the body field and let the app grasp, whether its an uri to deal with? (This would be the most simple approach).
- What validation of the links are requested? Just the protocols http: and app: ?
- Is this notification separate from the simple push notification and the action notification, is it a third type of notification?

**Comment by alireza-dhp** [comment]
Dear @andresgruber,

We suggest enabling clickable URLs in the Notification tab for improved functionality.
Upon tapping a push notification,please ensure that it directs users to the Notification tab instead of the Dashboard tab.

> * Will such a message contain title, body and (new) a link as a separate field in the API and in the study manager or would it be sufficient to use the body field and let the app grasp, whether its an uri to deal with? (This would be the most simple approach).

The simplest approach would suffice for now.
 
> * What validation of the links are requested? Just the protocols http: and app: ?

Validating http(s) links would be sufficient, and the implementation of opening an app (Deep links) may be explored for future development.

> * Is this notification separate from the simple push notification and the action notification, is it a third type of notification?

It's simply an enhancement to the existing simple push notification, providing a clickable URL in the body text.
 
> * Do you expect a data point for further evaluation, whether a participant has clicked on the notification?

At this stage, participant interaction data isn't necessary.

**Comment by andresgruber** [comment]
Requirements and Decision (2024/04/10):  Simple push notification should open the notification in the notification tab, then the link should active and clickable (http(s) links) only.

**Comment by ja-fra** [comment]
Enhancing the notification messages shows to be tricky on `iOS <15`.

After discussing with @janoliver20 we suggest the following approach:
* URLs will be clickable in `iOS 15+`
* For `iOS <14` we will keep the plain-text view (as it is now) - this affects less than [4% of all iOS devices](https://developer.apple.com/support/app-store/)

**Comment by alireza-dhp** [comment]
For iOS <=14, is it possible to copy a portion of the plain text (copy the link)?
