### ISSUE TITLE
Too Many Connection-Error Notifications for Polar-Observations

### ISSUE THREAD

**Issue by ja-fra** [MORE-Platform/more-app-multiplatform#261]
* For the Polar Verity observation, the device connection error message should not appear when there are no upcoming Polar observations scheduled. (**iOS** and **Android**)

* Sometimes the error message is displayed even when the device is connected. (**iOS**)

----
Originally raised by @alireza-dhp in https://github.com/MORE-Platform/more-app-multiplatform/issues/200#issuecomment-2167941076

**Comment by andresgruber** [comment]
With version 4.0.14 the behavior is that, the Error screen appears only at sign in and at days, where a polar observation is scheduled. 

Asking for connecting the external device at first registering as a participant seems useful, because one wants to check, whether the participant has access to the polar device at all.
